<div class="jumbotron">
	<h1>Trivia</h1>
	<p>This web app will help you run the perfect trivia night.</p>

	<form class="form-inline" role="form" method="post" action="/trivia/game/">
	  <div class="form-group">
	     <input type="text"  id="game-name" name="game_name" class="form-control btn-lg" style="font-size: 17.5px;   padding: 22px 19px;" placeholder="Name your game" />
	    <button type="submit" class="btn btn-primary btn-lg" role="button" id="create">Go</button>
	  </div>
	</form>
</div>
