<div class="jumbotron">
	<h1>Trivia</h1>
	<p>This web app will help you run the perfect trivia night.</p>

	<form class="form-inline" method="post" action="/game/">
	  <div class="form-group">
	     <input type="text"  id="game-name" name="game_name" class="form-control btn-lg" style="font-size: 17.5px; padding: 22px 19px;" placeholder="Name your game" autocomplete="off" />
	    <button type="submit" class="btn btn-primary btn-lg" id="create">Go</button>
	  </div>
	</form>
</div>
